version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: dms_meta
      POSTGRES_USER: dms
      POSTGRES_PASSWORD: dms
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./schema.sql:/schema/schema.sql:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dms -d dms_meta"]
      interval: 10s
      timeout: 5s
      retries: 5

  azurite-blob-storages:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    container_name: azurite-blob-storages
    command: ["azurite", "--location", "/data", "--blobHost", "0.0.0.0"]
    ports:
      - "10000:10000"
    volumes:
      - azdata:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10000/devstoreaccount1"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
  azdata: 